language: python
python:
- '2.7'
- '3.5'
sudo: false
notifications:
  email: false
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy h5py scipy
  pyopengl nose matplotlib pyqt cython dask
- source activate test-environment
- python setup.py build_ext --inplace
- python setup.py install
script: nosetests tests
deploy:
  provider: pypi
  user: gabriele.lanaro
  password:
    secure: RZiBFc7a7uAmxYJh5vXoP3eGBFNG9NiAApfWzc3O6b4WyTEFZ2NZUSlfcCghXwSs8Ydjy9herWbAxYGSkXZoM6KsX1B9RmFhcMiwb9nlnlsRFdUsqLuVpPXFZnHgsDxIzV/stNUd6sEBl4M+JgXg7JcSMxsdMcH7EDBfQ5WRFaI=
  on:
    tags: true
    repo: chemlab/chemlab
